name: dart_json_coverter_test
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  json_annotation: ^4.7.0 # Json -> Dart
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  # Testing
  test: ^1.16.0
  mockito: ^5.3.2
  # Json -> Dart
  build_runner: ^2.0.0
  json_serializable: ^6.4.0
